### ISSUE TITLE
I am new to GitHub and I have lots to say 

### ISSUE THREAD

**Issue by ydfdas1f546g1df** [ydfdas1f546g1df/streamSites#2]
I am new to GitHub and I have lots to say

I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/ydfdas1f546g1df/streamSites#installation

WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me.
STUPID FUCKING SMELLY NERDS

**Comment by M4rshe1** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING EXE!

**Comment by M4rshe1** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING EXE!
